# Generated by Django 6.0.5 on 2026-05-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_cleaned_title_video_codec_video_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcode_target',
            field=models.CharField(choices=[('original', 'Original (Streamable As Is)'), ('1080p', '1080p Full HD'), ('720p', '720p HD'), ('480p', '480p SD')], default='original', max_length=50),
        ),
    ]
