# Generated by Django 6.0.5 on 2026-05-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_video_hls_status_video_preview_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_required',
            field=models.BooleanField(default=False),
        ),
    ]
