# Generated by Django 6.0.5 on 2026-05-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_video_hls_status_alter_video_preview_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview_clip_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_required', max_length=20),
        ),
    ]
