# Generated by Django 6.0.5 on 2026-05-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_video_preview_clip_status_alter_video_preview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='has_custom_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
