# Generated by Django 6.0.5 on 2026-05-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_video_has_custom_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='streamable_copy_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
