# Generated by Django 6.0.5 on 2026-05-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_video_streamable_copy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hls_required',
            field=models.BooleanField(default=True),
        ),
    ]
