# Generated by Django 6.0.5 on 2026-05-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_video_hls_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='streamable_copy_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_required', max_length=20),
        ),
    ]
