# Generated by Django 6.0.5 on 2026-05-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_video_streamable_copy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='streamable_copy_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
