# Generated by Django 6.0.5 on 2026-05-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_video_streamable_copy_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='streamable_copy_status',
        ),
    ]
